#' Data for exemples
#'
#' Simulated data to use in coiR package functions. Canopy images as a SpatRast class objecr, from \href{https://rspatial.github.io/terra/}{terra} package (see details).
#'
#' @format A set list with 4 images, with different canopy openness:
#'
#' @source Images manually shotten by author using a fisheye lens, not generated by AI.
#'
#' @details images are setted by a list of 4 rasters (SpatRast class). Pay attenction to exemple to know how procede with a single isolated image and a list of images.
#'
#' @examples
#'
#' # Load packages
#'
#' library(coiR)
#'
#' # Importing data
#'
#' \donttest{
#' images <- coiR::data_coir()
#'
#' # Visualizing
#'
#' purrr::map(images, \(caminho){
#'
#'   imagem <- caminho |> terra::rast()
#'
#'   ggplt <- ggplot2::ggplot() +
#'    tidyterra::geom_spatraster_rgb(data = imagem)
#'
#'   print(ggplt)
#'
#'   })
#' }
#'
#' @export
#'
data_coir <- function(){

  caminho <- system.file("extdata", package = "coiR")

  arquivos <- list.files(caminho,
                         full.names = TRUE,
                         pattern = "\\.(jpg|jpeg|png)$")

  arquivos

  }
