#' Data for exemples
#'
#' Simulated data to use in coiR package functions. Canopy images as a SpatRast class objecr, from \href{https://rspatial.github.io/terra/}{terra} package (see details).
#'
#' @format A set list with 4 images, with different canopy openness:
#'
#' @source Images manually shotten by author using a fisheye lens, not generated by AI.
#' 
#' @details images are setted by a list of 4 rasters (SpatRast class). Pay attenction to exemple to know how procede with a single isolated image and a list of images.
#' 
#' @examples
#'
#' # Load packages
#'
#' library(coiR)
#'
#' library(purrr)
#'
#' # Importing data
#'
#' images <- coiR::data_coir()
#'
#' # Visualizing data
#' 
#' visualizing_images <- function(image){
#' 
#'   ggplt <- ggplot() +
#'    tidyterra::geom_spatraster_rgb(data = image) +
#'    theme_void()
#'   
#'   print(ggplt)
#' 
#' }
#' 
#' purrr::walk(images, visualizing_images)
#' 
#' @export
#' 
data_coir <- function(){
  
  img_files <- list.files(path = "C:/Users/LENOVO/OneDrive/Documentos/coiR/cropped-images",
                          pattern = ".png",
                          full.names = TRUE)
  
  imgs <- lapply(img_files, terra::rast)
  
  names(imgs) <- img_files |> basename() |> stringr::str_remove(".png")
  
  return(imgs)
  
}
